### ISSUE TITLE
Using HTTPS with the self hosted deployment

### ISSUE THREAD

**Issue by kashyapanup** [useplunk/plunk#110]
I'm new here. Not sure if this is the right place to ask. Is there any additional configuration needed to support the deployment with HTTPS. I tried setting up a nginx reverse proxy to terminate SSL. But I'm not able to login as it is still trying to access the API with HTTP which throws a mixed content error.

**Comment by serge005** [comment]
Did you set your Project Settings URL to the new https endpoint?

**Comment by kashyapanup** [comment]
I've updated the APP_URI and APP_URI in the environment variables. Where should I set the project settings URL?

**Comment by driaug** [comment]
Closing as inactive.

**Comment by dentro-innovation** [comment]
I'm always using Caddy to expose my self hosted web apps and retrieving SSL certificates. 
Much simpler than nginx imo.

Install caddy:
```
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg && \
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list && \
apt update && \
apt install caddy;
```

create a new `Caddyfile` ( I also change the port in docker-compose.yml to `"127.0.0.1:3000:3000"` to make sure that it can't be accessed without going through caddy):
```
plunk.dentro-innovation.com {
    # Compress responses
    encode gzip zstd

    # Handle API and web requests
    handle {
        # Reverse proxy to the Plunk service
        reverse_proxy localhost:3000
    }

    # Log all requests
    log {
        output file .plunk.log
        format json
    }
}
```

Then just run `caddy stop` and `caddy start` from within the directory as the Caddyfile.
