### ISSUE TITLE
MessageRejected: Email address is not verified

### ISSUE THREAD

**Issue by amosbastian** [useplunk/plunk#111]
I'm self hosting Plunk and trying to trigger an event that will then send an email to e.g. john@example.com.

```ts
await plunk.events.track({
  event: "my-event",
  email: "john@example.com",
  subscribed: true,
});
```

But when I trigger the event Plunk stops working (logs me out, can't log back in until I restart the container) and logs the message

```
MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-1: john@example.com
```

It seems like it's trying to send the email with the email of the user who I'm triggering the event for 🤔

**Comment by amosbastian** [comment]
> Hi!
> 
> Is your AWS SES instance still in sandbox mode or is it already approved?

I thought it was, but I think that was in another region 🤦 I guess it's that

**Comment by driaug** [comment]
Exactly, as long as you are in the sandbox mode you are only able to send messages to a verified admin email of the AWS account.
