### ISSUE TITLE
Track Event API call with "subscribed": false is not unsubscribing contact

### ISSUE THREAD

**Issue by ejscheepers** [useplunk/plunk#112]
I have been trying to use https://docs.useplunk.com/api-reference/actions/track to unsubscribe a contact, but I cannot get it to work, might be a bug where client is always subscribed when /track api is used.

Here are some logs:

Track event payload: {
  "event": "customer_updated_shopify",
  "email": "eugene0scheepers@gmail.com",
  "subscribed": false
}

Sending POST request to: https://plunk.send-kit.com/api/v1/track

Track event API response: {
  "success": true,
  "contact": "ce0188f5-85f0-49cc-a63e-b4a4e1afadba",
  "event": "f1797c0a-9224-4b70-828d-7d09c0b398b6",
  "timestamp": "2024-10-15T12:36:45.791Z"
}

So the api call is successfull, but the client is still subscribed...

<img width="1127" alt="Screenshot 2024-10-15 at 14 42 41" src="https://github.com/user-attachments/assets/781d37fc-6b7e-4737-94b5-bb1925357fba">

**Comment by ejscheepers** [comment]
Created a PR to fix: https://github.com/useplunk/plunk/pull/113

**Comment by driaug** [comment]
Fixed by #113
