### ISSUE TITLE
Can't create events on app.useplunk.com

### ISSUE THREAD

**Issue by digitaldrreamer** [useplunk/plunk#117]
[Video_2024_10_28-1.webm](https://github.com/user-attachments/assets/bc0043dc-0be4-4a75-9677-cf277820f6c5)

**Comment by driaug** [comment]
Could you please show me the error that is possibly shown in the console of your developer tools?

**Comment by digitaldrreamer** [comment]
It shows a 500:
![Screenshot_2024_10_28-1](https://github.com/user-attachments/assets/a03134fa-fe80-4315-8911-d99e84453ce4)

The actual response:
```javascript
{
    "code": 500,
    "error": "Internal Server Error",
    "message": "\nInvalid `prisma.trigger.create()` invocation:\n\n\nForeign key constraint violated: `triggers_eventId_fkey (index)`",
    "time": 1730116590611
}
```

**Comment by driaug** [comment]
Assuming this is a caching issue. Did you by any chance recently delete and recreate this event?

**Comment by digitaldrreamer** [comment]
Yes actually. Just now 🥲

Lemme clear my  cache then

**Comment by digitaldrreamer** [comment]
Perhaps I'll try again in a few hours then.

**Comment by digitaldrreamer** [comment]
Works now. Seems the cache has been cleared. Thanks @driaug
