### ISSUE TITLE
Confusing MX record [self hosting]

### ISSUE THREAD

**Issue by dentro-innovation** [useplunk/plunk#129]
Following the guide in the self hosted plunk dashboard:
![image](https://github.com/user-attachments/assets/0e7b40fd-3c56-43a2-b67d-0a0b10905439)

I should add an MX record `feedback-smtp..amazonses.com`. 

However, in my namechap dashboard I can't add this value, this double period without anything in between.

What's actually happening, is that namecheap automatically replaces it with "undefined": `10 feedback-smtp.undefined.amazonses.com`. 
While writing this github comment, I just realized that the insertion of "undefined" happens it this very textbox here as well, and it other messengers too. 

This makes me think that there's probably some bug, and it should show `10 feedback-smtp.MYDOMAIN.amazonses.com`, shouldn't it?

**Comment by driaug** [comment]
This likely means that you have not correctly configured the `AWS_REGION` environment variable. 

Place the AWS region where your SES instance is running in between the dots and you get the correct record.

Like `feedback-smtp.us-east-1.amazonses.com`

**Comment by dentro-innovation** [comment]
Okay thanks! 

I think I do set up the region correctly, this is in my .env file: `AWS_REGION=eu-central-1`.

Fixed the MX record for now thank you.
