### ISSUE TITLE
Events page seems like its not loading [self hosted]

### ISSUE THREAD

**Issue by dentroai** [useplunk/plunk#130]
When I open the events page on my self hosted plunk I see the "loading" screen, but nothing loads:
![image](https://github.com/user-attachments/assets/18984780-8c54-4619-842a-237f8eaae722)
 
This seems odd, is this to be expected?

**Comment by driaug** [comment]
Do you see any errors in the network tab of your developer settings?

**Comment by dentro-innovation** [comment]
Seems pretty green on firefox:
![image](https://github.com/user-attachments/assets/688d6168-d1ac-4161-81ae-2d79c1f27bc9)

As well on Chrome:
![image](https://github.com/user-attachments/assets/ea6a41c3-9106-4595-8523-d9965de11199)

**Comment by dentro-innovation** [comment]
ok I just successfully sent my first email with Plunk from hello@domain1.com, and now the events page is loading normally!

However, the events page of another plunk project where I haven't yet send any emails, it still shows the "loading" events page. 

Guess it needs some data to display correctly.
