### ISSUE TITLE
How to interpret AWS console recommendation to set up DMARC records? [self hosted] [question]

### ISSUE THREAD

**Issue by dentro-innovation** [useplunk/plunk#131]
I just sent my first email successfully with my self hosted plunk.

Now in my AWS console I can see this:
![image](https://github.com/user-attachments/assets/8ba51393-20a3-4cba-a96e-5909abdc1abc)

AWS recommends me to set up DMARC DNS records. 

Is this a good idea or might it mess something up with plunk, as plunk already told me set up some DKIM and SPF records?

**Comment by driaug** [comment]
You are perfectly fine setting up DMARC records. 

DMARC is a record that tells email servers what they should do with an email when it fails DKIM or SPF checks. If you do not set a DMARC record, each server will decide what they do (send it to the inbox, send it to spam, or refuse the message). If you set a DMARC record, you get back that control!

There are no specific requirements for DMARC with Plunk. 
This explains the concept really well => https://www.cloudflare.com/en-gb/learning/dns/dns-records/dns-dmarc-record/
