### ISSUE TITLE
How to split up AWS resources for multiple domains and transactional vs. marketing emails? [self hosting] [question]

### ISSUE THREAD

**Issue by dentroai** [useplunk/plunk#132]
Sorry for spamming the github issues, I just happen to not be an expert with AWS and emails in general; and perhaps others will have the same questions so we can document them here.

I just set up my self hosted plunk successfully, and want to request production access for my AWS SES setup:
![image](https://github.com/user-attachments/assets/4e3bec87-83d4-498a-81b8-b3f05facefd2)

Two things come to my mind:

1. I have to choose either marketing or transactional emails. But Plunk does both, doesn't it?
2. I have to specify the URL to my website. I plan to use a single plunk instance for multiple domains, which means the same AWS SES configuration set for multiple domains (I can only specify a single SES configuration set per plunk instance right?). 
But I can only specify a single URL in the AWS interface above.

Do I just select anything and then make sure I don't send spammy content and everything will be fine?

**Comment by driaug** [comment]
When verifying your setup with Amazon. 

- Select marketing if you will be sending both marketing and transactional
- Link the most reputable version of your company's website

The most important part is the open text field that comes after where you describe how often you will send emails, the content, complaint handling.
