### ISSUE TITLE
how to use smtp when self hosting? [self-hosting] [question]

### ISSUE THREAD

**Issue by dentro-innovation** [useplunk/plunk#134]
In the docs I can see how to use smtp with the hosted version of plunk: https://docs.useplunk.com/getting-started/smtp

![image](https://github.com/user-attachments/assets/13e4db00-196d-46b4-8c64-5eb6c68fbf03)

How can I do the same on the self hosted version?
I don't seem to have smtp.mydomain.com, also the docker compose setup doesn't seem to expose any smtp ports.

**Comment by driaug** [comment]
The self-hosted version of Plunk does not contain the SMTP endpoint. 

The required code to run it yourself can be found in #46 but will have to set up your own certificates to run a secure SMTP endpoint.
