### ISSUE TITLE
Managing Access for Self-Hosted Instances

### ISSUE THREAD

**Issue by Jannik-Schroeder** [useplunk/plunk#14]
If you host it yourself, for example at home, you don't want everyone to be able to log in and send a large number of emails from your IP address or your instance. I initially considered simply putting it behind an ACL on my web server, but then you encounter the issue that AWS SNS can no longer access the API, and users have no way to unsubscribe. Therefore, it would be beneficial if you could disable the login on private instances through, for example, a variable or a database entry.

**Comment by Jannik-Schroeder** [comment]
Nice this is a really good change to increase the security of the instance but the variable should be in standard boolean format.

**Comment by driaug** [comment]
`process.env` variables are automatically parsed as strings in TS, unlike the YAML spec which does allow a variety of boolean values. I believe an explicit `true/false` field is easiest here but could be refactored later down the line.
