### ISSUE TITLE
ReplyTo email id gets replaced with the From Email Id for SMTP

### ISSUE THREAD

**Issue by abishekrsrikaanth** [useplunk/plunk#141]
I am on the paid plan and I use SMTP to send emails through Plunk. When using SMTP to send emails, the ReplyTo email id gets replaced with the From Email Id.

**Comment by driaug** [comment]
Reply-to is currently not supported by the SMTP service of Plunk.

**Comment by abishekrsrikaanth** [comment]
@driaug Any chance this can be supported. Most top providers support this and we really want to switch to using Plunk and this is a show stopper for us. We use Wordpress for our stores and SMTP is the only way to go to use Plunk.
