### ISSUE TITLE
Could not add domain

### ISSUE THREAD

**Issue by oalexdoda** [useplunk/plunk#143]
Hi,

On a self-hosted instance (Coolify), when you try to add a custom sending domain it errors with "Could not add domain.". No error message or further explanation.

Any clue on what to do?

Thanks!

**Comment by driaug** [comment]
Is there an error in the logs of the API?

**Comment by oalexdoda** [comment]
The project in question wasn't accepted by Amazon SES for some reason so we removed the instance for now. I'll go ahead and close the issue. Thanks!
