### ISSUE TITLE
Control AWS Account Access for Email Sending

### ISSUE THREAD

**Issue by Jannik-Schroeder** [useplunk/plunk#15]
The AWS account is currently managed through the ENV variable, which means anyone with access to the environment can create their own account and send emails using my AWS account, incurring costs that I have to cover.

### Problem:

- Any user can create their own account.
- All emails are sent through my AWS account, leading to potential unexpected costs.

### Proposed Solution:

- Implement a method to restrict the use of the AWS account to specific users.
- Add an authentication method to control who can use the AWS account for sending emails.
- Consider using the AWS account only for administrative tasks or trusted users.

**Comment by driaug** [comment]
This would be fixed by implementing https://github.com/useplunk/plunk/issues/14, no?

Disabling signups through the environment variables would prevent other using from using the Plunk instance.

**Comment by Jannik-Schroeder** [comment]
Yes #14
