### ISSUE TITLE
Analytics page shows NaN if no data available

### ISSUE THREAD

**Issue by driaug** [useplunk/plunk#16]
The [analytics page](https://github.com/useplunk/plunk/blob/main/packages/dashboard/src/pages/analytics/index.tsx) shows NaN when no data is available.

This would be a very good first fix for someone that is looking to contribute!

![image](https://github.com/user-attachments/assets/ba32773b-084c-4ff5-9dda-66be3e8607a9)

**Comment by pabllot** [comment]
can I take it?

**Comment by driaug** [comment]
Closed by #24, thank you for the help!
