### ISSUE TITLE
Add Version Tagging to Docker Build Workflow

### ISSUE THREAD

**Issue by Jannik-Schroeder** [useplunk/plunk#21]
#### Problem

Currently, the Docker build and push workflow does not include version tagging based on the `package.json` version. This can lead to difficulties in tracking and deploying specific versions of the Docker image, making it harder to manage and roll back to previous versions if needed.

#### Proposed Solution

Integrating version tagging in the Docker build and push workflow would address this issue by using the version specified in `package.json`. This approach ensures that each Docker image is tagged with the corresponding application version, facilitating better version control and deployment management.

#### Benefits

- **Improved Version Control**: Tags Docker images with the application version, making it easy to identify and use specific versions.
- **Enhanced Deployment Management**: Simplifies the process of deploying specific versions to different environments, reducing the risk of deploying incorrect versions.
- **Ease of Rollback**: Enables straightforward rollback to previous versions if issues arise, improving application stability and reliability.

#### Implementation Steps

1. **Extract Package Version**: Add a step in the workflow to extract the version from `package.json`.

   ```yaml
   - name: Extract package version
     id: package_version
     run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

2. **Use Extracted Version for Tagging:** Modify the Docker build and push steps to use the extracted version for tagging the Docker image.
   ```yaml
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=raw,value=${{ steps.package_version.outputs.version }}
          type=raw,value=latest

3. **Update Workflow Configuration:** Adjust the workflow configuration to include the extracted version in the tags and metadata for the Docker image.

By implementing these steps, the workflow will automatically tag Docker images with the appropriate version from package.json, enhancing overall version management and deployment processes.

**Comment by driaug** [comment]
This is a pretty urgent one, I would love if we can make it automated on merge to `main`.

**Comment by Jannik-Schroeder** [comment]
> This is a pretty urgent one, I would love if we can make it automated on merge to `main`.

So the last commit would create a new package on each merge to main, but you have to manually increment the version, I could change it so that on a merge to main the version is automatically incremented by a command, but I see a problem with the branch protection rule on main. Maybe there is a setting to turn this off for a ci user, would have to look it up.

**Comment by Jannik-Schroeder** [comment]
It took me a while but i think i found a proper way to do it and explained it in the PR: https://github.com/useplunk/plunk/pull/23#issuecomment-2267617483

The only Downside i see, you have to merge 2 pull requests for a new version on main instead of one.

**Comment by driaug** [comment]
Thank you very much for your PR on this Jannik! Even though I did not end up using it, it did show me the right way of doing it.

We now extract the `version` from `package.json` and push that as the version to Docker Hub :)
