### ISSUE TITLE
webhook/event notifications for emails

### ISSUE THREAD

**Issue by tttp** [useplunk/plunk#37]
Hi,

amazon offers the option to set up wehooks to inform the sending application when something goes wrong (bounce, unsubscribe, flagged as spam...)

https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity-using-notifications.html

Is it be possible to either set up the endpoint in amazon or having plunk redirect them them to the calling application?

**Comment by driaug** [comment]
If you self-host Plunk you are able to this.

https://docs.useplunk.com/getting-started/self-hosting#1-1-sns-topic

You need to set up your own SES topic to fully benefit from Plunk and are able to set up a 2nd subscription next to the one needed for Plunk. You cannot do this with the managed version.
