### ISSUE TITLE
is it possible to cancel a pending event?

### ISSUE THREAD

**Issue by tttp** [useplunk/plunk#38]
Hi,

I'd like to send in a message in a week time (eg. "your trial period is ending") and I see I can set up that workflow 

However, is it possible to "unschedule" this message (for instance if the user upgrades their subscription between now and a week's time)?

**Comment by driaug** [comment]
Yes! If you link your upgrade event as a `Exclude contacts with triggers` event then it will exclude users that have triggered it when it tries to send the email automatically. No need to manually "unschedule" the email.
