### ISSUE TITLE
self hosted AWS setup

### ISSUE THREAD

**Issue by Stunt0265** [useplunk/plunk#40]
Two issues.  Using this as a guide:

https://docs.useplunk.com/getting-started/self-hosting

1- They list "/api/webhooks/incoming/sns" in their instructions, but the screenshot they show "/api/webhooks/sns"

2- And when attempting to create the subscription, AWS doesn't allow it due to the endpoint not existing yet and produces the error "Couldn't create subscription"

**Comment by driaug** [comment]
1. This is definetly a mistake, the correct endpoint is /api/webhooks/incoming/sns

2. I'm not sure what you are doing to encounter this error, I cannot replicate it on my end

**Comment by driaug** [comment]
I've gone ahead and updated the screenshot in the documentation!

**Comment by Stunt0265** [comment]
![sns-error](https://github.com/user-attachments/assets/1a9a2561-56af-4b64-b3cc-10593343b52c)

**Comment by driaug** [comment]
Thank you for sharing that!

I have moved the creation of the SNS subscription to the end of the self-hosting guide.
This means that Plunk will be running and you should have domain set up.
