### ISSUE TITLE
MJML Templating Support

### ISSUE THREAD

**Issue by danielloader** [useplunk/plunk#42]
Hey! Just stumbled on this project and thought I'd get in early and ask for https://mjml.io/ support in addition to react email/jsx email support.

This is purely self interest as I already have MJML templates to use and porting it all to a react flavour would be a reasonable amount of effort.

Thanks

**Comment by driaug** [comment]
Hey!

Plunk also does not have direct support for JSX Email/React Email. You compile those templates into HTML which you can give to Plunk, you do the exact same with MJML so it is fully compatible!

**Comment by danielloader** [comment]
Ah okay, I know there's an implementation of MJML for the browser, by default it's a node/backend library usually exposed via express etc so figured I'd ask if that would be worth [embedding for server side](https://documentation.mjml.io/#inside-node-js) rendering down to HTML.

If not it's fine I can make it work, just means hosting another container in a compose stack I guess.
