### ISSUE TITLE
Consider adding a License

### ISSUE THREAD

**Issue by TheBinaryGuy** [useplunk/plunk#6]
Hey, I found this via your tweet and congrats on the launch!

I noticed that there is no License attached, if the project is meant to be open source, then please consider adding a license.

https://choosealicense.com/no-permission

Thanks.

**Comment by fakerybakery** [comment]
The package.json `license` field is set to MIT (https://github.com/useplunk/plunk/blob/27a799fa996f0e5fa97e932e8221bb206273e078/package.json#L5), would be nice if the authors could add a license file to clarify though.

**Comment by driaug** [comment]
Very much in favour of adding a license, the MIT in the `package.json` is a remnant from time long gone.

Licensing is not my strong suit so very open to advice from the community here!

**Comment by TheBinaryGuy** [comment]
I second @fakerybakery suggestion.

Another option would be a copy left license, like AGPL, if you want people to open source their modifications as well.

**Comment by Stancobridge** [comment]
I second @TheBinaryGuy suggestion.

Using a licence that allows more flexibility with a copy left licence

**Comment by driaug** [comment]
Plunk is now licensed as `AGPL V3`, thank you for the feedback!
