### ISSUE TITLE
Using existing AWS SES account

### ISSUE THREAD

**Issue by Jaarson** [useplunk/plunk#67]
I have a question about using my existing AWS SES account, which already has identity, DKIM, SPF, etc., set up and is currently being used to send emails (not via Plunk yet)

Can I use this account when self-hosting Plunk?

**Comment by driaug** [comment]
You can! 

- Set up an SNS topic if you have not done that and link it up to the webhook endpoint of Plunk.
- Reuse your AWS credentials when deploying
- Create a new project and link the domain from your AWS account, it will automatically verify
