### ISSUE TITLE
Add template support in API and SMTP

### ISSUE THREAD

**Issue by jdkanani** [useplunk/plunk#68]
The API and SMTP currently only accept the email body, not templates and variables. Adding this feature would be great. Loops has a good example: https://loops.so/docs/api-reference/send-transactional-email. 

Something similar in Plunk would be ideal.

**Comment by driaug** [comment]
This feature will probably not be added soon.

It used to be part of the features a long time ago with very low usage compared to the complexity.

**Comment by dentroai** [comment]
not sure if that's related, but I'd like to pass in variables to templates. 

E.g. the name of the user in a welcome email.
