### ISSUE TITLE
[Feature] Add custom Reply-To header to Templates or Project Settings

### ISSUE THREAD

**Issue by memen45** [useplunk/plunk#70]
Would love a feature where I can send automated mail from my verified domain (e.g. `noreply@mydomain.com`) and set a Reply-To header in the mail template / settings so that contacts' replies will be sent to another email address (e.g. mydomain@gmail.com).

**Comment by driaug** [comment]
I do not setting the reply-to to a different domain than the sending domain. 
This is a very common thing spammers do.

May I recommend setting up a forwarding service, like https://improvmx.com, instead?

**Comment by memen45** [comment]
Thank you. That might be a better solution!
