### ISSUE TITLE
Domain Verification Records incorrect for subdomains

### ISSUE THREAD

**Issue by driaug** [useplunk/plunk#71]
If you verify a subdomain in the dashboard, the records required aren't correctly displayed and only show the root domain.

For example the records for verifying `mail.useplunk.com`, will be shown as:
- `domainverificationtoken_domainkey`

While they should be
- `domainverificationtoken_domainkey.mail`

The file in the dashboard that hosts this code is: https://github.com/useplunk/plunk/blob/main/packages/dashboard/src/pages/settings/identity.tsx

The project that contains the email that is currently waiting for verification is in `activeProject.email`

**Comment by nklmantey** [comment]
@driaug is this issue still open?

**Comment by driaug** [comment]
This one is still open!

**Comment by nklmantey** [comment]
great!

**Comment by nklmantey** [comment]
opened a pr to fix this https://github.com/useplunk/plunk/pull/116

**Comment by driaug** [comment]
Thank you for your contribution!

Closed by #116
