### ISSUE TITLE
"Unlink domain" does not work

### ISSUE THREAD

**Issue by memen45** [useplunk/plunk#72]
During setup, I have removed DNS entries at some point. In the project settings > Verified domain it still shows "Domain Verified". Using the "Unlink domain" option reloads the page, but nothing changes. I also cannot find the DNS entries that were required for useplunk. 
Mailing seems to work, but I am not sure for how long or if mails will go to spam folders directly.

**Comment by driaug** [comment]
Hi.

Is this for the hosted version of Plunk or are you self-hosting.

If it is the hosted version, send me your project and I will take a look.

**Comment by memen45** [comment]
It is on the hosted version. How can I send you the project?

**Comment by driaug** [comment]
> It is on the hosted version. How can I send you the project?

Twitter, support@useplunk.com or via our Discord server.

**Comment by memen45** [comment]
Thanks for your fast replies! Is there a way to export the project or give access to you over email? Or do you need the project name only?

**Comment by driaug** [comment]
I just need the project name!
