### ISSUE TITLE
Pasting an link with a template tag breaks the template

### ISSUE THREAD

**Issue by nik-lampe** [useplunk/plunk#75]
I stumbled across this, when setting up the double opt-in as described in the documentation.

When I create a new template, and just paste this link: `https://example.com/subscribe/{{plunk_id}}`. It doesn't really matter if there is any other text in the template, then it get's saved like this in the database:

```<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://example.comsubscribe/{{plunk_id">https://example.com/subscribe/{{plunk_id</a>}}</p>```

Note the missing `}}` in the href and the closing a tag before the closing brackets.
This has the effect that the email when rendered does not have any body at all.

**Comment by driaug** [comment]
Fixed by #80
