### ISSUE TITLE
Feature Request: Add form-data route for track events

### ISSUE THREAD

**Issue by nik-lampe** [useplunk/plunk#77]
Currently it seems, that it is only possible to send track events with a JSON payload. 

But for example to integrate a form into a website, where users can sign themselves up via a simple HTML form it would be nice to have an endpoint that parses the form-data body but then works exactly like the track postEvent.

**Comment by driaug** [comment]
This is not on the roadmap for now.

An intermediate step through an app like Zapier is recommended for this.
