### ISSUE TITLE
Self Hosted Signup Using Incorrect API URL

### ISSUE THREAD

**Issue by apardes** [useplunk/plunk#83]
Howdy! I'm running Plunk with Docker but when I try to sign up the page just hangs. Checking the browser console I see this:

<img width="492" alt="Screenshot 2024-09-09 at 10 22 34 PM" src="https://github.com/user-attachments/assets/428a8966-2aa3-42a0-ad93-aabce16354de">

These are the env vars in my `compose.yaml` file:

```
      NEXT_PUBLIC_API_URI: 'http://plunk.mydomain.com/api'
      API_URI: 'http://plunk.mydomain.com/api'
      APP_URI: 'http://plunk.mydomain.com'
```

Why isn't the URL for that request correct?

**Comment by apardes** [comment]
In a private browser window the API URL is correct but I'm getting this error similar to #44 

<img width="399" alt="Screenshot 2024-09-09 at 10 46 52 PM" src="https://github.com/user-attachments/assets/28c2a1e5-9f7b-4a43-a9fa-ce2a8cca91c1">

**Comment by apardes** [comment]
@driaug I tried updating my env vars 

```
      NEXT_PUBLIC_API_URI: 'http://plunk.mydomain.com:3000/api'
      API_URI: 'http://plunk.mydomain.com:3000/api'
      APP_URI: 'http://plunk.mydomain.com:3000'
```

and the previous error goes away but now just getting a 401 response for any form submission. A

Any thoughts?

**Comment by driaug** [comment]
Hey there! Plunk needs to be running on HTTPS to work.
