### ISSUE TITLE
Serve Self Hosted Plunk Over SSL

### ISSUE THREAD

**Issue by apardes** [useplunk/plunk#84]
Like the title says, is it possible to serve self hosted Plunk over SSL?

**Comment by driaug** [comment]
I host it through https://coolify.io/ which takes care of the certs for me. 

It is definitely possible but I don't immediately have docs for it. 
I know there are a couple of folks that do run it with no extra layers, so I will be marking this as a question and leaving it open for others to answer.

**Comment by salihcodes** [comment]
Yes, you can. I have it running on a coolify instance. You should be good to go once you configure a custom domain and add the appropriate DNS records.
