### ISSUE TITLE
Bad Request; Invalid email address; status 400

### ISSUE THREAD

**Issue by ertush** [useplunk/plunk#91]
I have been trying to send a transactional email from an app running on localhost. I tried to follow plunks documentation on sending an email using the REST API endpoint [https://api.useplunk.com/v1/send"](https://api.useplunk.com/v1/send") but I end up getting the following response 
The request is: 
```
body: {
    to: 'alex.jacob@gmail.com', // I have used the email registered in plunk
    subject: 'Testing Personal Contact Form',
    body: 'Test Message',
    subscribed: true,
    name: 'user',
    from: 'jane.doe@gmail.com',
    reply: '',
    headers: {}
  }
```
The response:
```
response: {
    code: 400,
    error: 'Bad Request',
    message: 'Invalid email address',
    time: 1726489128309
  }
 ``` 
 The following is my code
 
![image](https://github.com/user-attachments/assets/0fee7a98-9c39-4483-90db-c94b62d8c29c)

Please let me know what I am doing wrong

**Comment by driaug** [comment]
The `from` address you are specifying, it needs to be under the domain that you have verified in Plunk.

Can you confirm that this is the case?

**Comment by driaug** [comment]
Also, I believe that the issue of your bug is that your are specifying `reply` but setting it to an empty string. 

Either specify a `reply-to` email address or don't pass the `reply` parameter.

**Comment by ertush** [comment]
I am using my verified email in the `from` field of the body

**Comment by ertush** [comment]
> Also, I believe that the issue of your bug is that your are specifying `reply` but setting it to an empty string.
> 
> Either specify a `reply-to` email address or don't pass the `reply` parameter.

Let me try this

**Comment by ertush** [comment]
It worked. Thanks for your help. The issue was the reply parameter of request body

**Comment by ertush** [comment]
Also I would suggest you add that info in the  documentation. It will help in case someone else comes across  the same problem
