### ISSUE TITLE
Calling /api/tasks works unauthenticated 

### ISSUE THREAD

**Issue by raphaelm-gioa** [useplunk/plunk#92]
The scheduled jobs to send the emails is under a different controller in `packages/api/src/controllers/Tasks.ts`
The handleTasks function is missing the `@Middleware([isAuthenticated])` attribute.

I expected this endpoint to be present in the API Documentation, and to be protected by the Bearer Token!
Does it only miss the `@Middleware([isAuthenticated])` attribute ?

**Comment by driaug** [comment]
There is no reason for this endpoint to be in the API documentation or to be authenticated.
It is an internal endpoint that does not accept nor returns any data.

**Comment by raphaelm-gioa** [comment]
This endpoint is used internally for the sending of all scheduled emails, and it also doesn't return any data : all true
But it feels like a security issue to me to have a public API that could trigger email sending
