### ISSUE TITLE
Verify multiple addresses

### ISSUE THREAD

**Issue by YouKnowBlom** [useplunk/plunk#94]
As far as I understand it, currently it's only possible to verify and send from one single email (for example `plunk@plunk.com`). It would be nice to be able to verify multiple emails addresses, or a whole domain (for example `*@plunk.com`)

P.S. Thank you for a great service! :)

**Comment by YouKnowBlom** [comment]
I appreciate the quick reply!

That sounds promising! Is this also available via SMTP or only through the API?

**Comment by driaug** [comment]
Also available for SMTP!
